version: '3'

services:
  nginx-autoindex:
    container_name: nginx-autoindex
    build:
      context: .
    image: dceoy/nginx-autoindex:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}:/var/www/html:ro
